### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Avizacherman** [ArdisM/game-name-here#1]
Ardis,

Really great work here. I like how you took something we did in class, built up it's complexity and gave it a front-end. Ash also showed me that you can poke it's eye out which is so mean.  

One thing I will say about your code is get used to indenting to make it easier to read. It doesn't matter to the computer, but other humans in the future will read what you wrote and indents help make code cleaner. I would love to see you refactor this and 'pretty' it up a bit. 

What other functions could you add to Blobby to make him live?

**Comment by ajhofferber** [comment]
Hey Ardis,

I agree with Avi! It's a cool way to take the tomagatchi idea to the next level and continue to add in features. I am curious, though, what does the "lives" text input box do in your game? Not sure what it's role is, but it could be just me!

Is there a way that you could adjust your game where it is keeping a score? Like you get docked points for hurting or getting your blobby sick? 

Overall, your game meets the project requirements and is fun to play around with! Nice job!

Score: 2/3 (refer to project markdown for score rubric)

-Ash
